// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8K8ZdVvf5hO6eJ_v9Q1_-M_7S1KzChEg',
    appId: '1:589236248483:web:88b03fc4b1307430388416',
    messagingSenderId: '589236248483',
    projectId: 'authentication-2faa8',
    authDomain: 'authentication-2faa8.firebaseapp.com',
    storageBucket: 'authentication-2faa8.appspot.com',
    measurementId: 'G-32SY8T5WL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZAADafB-nS8dXVbYwehIZwitl82gSKYI',
    appId: '1:589236248483:android:e637088ca8142d4c388416',
    messagingSenderId: '589236248483',
    projectId: 'authentication-2faa8',
    storageBucket: 'authentication-2faa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsg0XB2KUHqZzZUJef1PgSV1GJyZ17JFY',
    appId: '1:589236248483:ios:b2d4e540fb7f040e388416',
    messagingSenderId: '589236248483',
    projectId: 'authentication-2faa8',
    storageBucket: 'authentication-2faa8.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsg0XB2KUHqZzZUJef1PgSV1GJyZ17JFY',
    appId: '1:589236248483:ios:b2d4e540fb7f040e388416',
    messagingSenderId: '589236248483',
    projectId: 'authentication-2faa8',
    storageBucket: 'authentication-2faa8.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8K8ZdVvf5hO6eJ_v9Q1_-M_7S1KzChEg',
    appId: '1:589236248483:web:4de4c245fcc0deda388416',
    messagingSenderId: '589236248483',
    projectId: 'authentication-2faa8',
    authDomain: 'authentication-2faa8.firebaseapp.com',
    storageBucket: 'authentication-2faa8.appspot.com',
    measurementId: 'G-7K867SQ6BD',
  );
}
